version: '3'

services:
  minetrack:
    image: minetrack:latest
    container_name: minetrack
    ports:
      - "80:8080"
    volumes:
      - ./database.sql:/usr/src/minetrack/database.sql
      - ./servers.json:/usr/src/minetrack/servers.json
      - ./favicons/:/usr/src/minetrack/favicons/
    restart: always
